# Generated by Django 5.2.5 on 2025-09-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_sitelogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('publish_date', models.DateField()),
                ('read_time', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='stock_images/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
