# Generated by Django 5.2.5 on 2025-09-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='read_time',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='Stocks', max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
