# Generated by Django 5.2.5 on 2025-09-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_blog_publish_date_remove_blog_read_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(upload_to='users/')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
