# Generated by Django 5.2.5 on 2025-09-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_realtimeuser_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('highlight', models.TextField(blank=True, null=True)),
                ('partner_text', models.CharField(blank=True, max_length=255, null=True)),
                ('small_text', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='expertise_images/')),
            ],
        ),
    ]
