# Generated by Django 5.2.5 on 2025-09-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_feature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpertiseSection',
            new_name='Expertise',
        ),
    ]
