# Generated by Django 5.2.5 on 2025-09-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_expertisesection_expertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='promo_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Expertise',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
