# Generated by Django 5.2.5 on 2025-09-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_promoimage_delete_expertise_delete_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='step_icons/')),
            ],
        ),
    ]
