# Generated by Django 5.2.5 on 2025-09-04 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_businesscard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscard',
            name='description',
        ),
        migrations.RemoveField(
            model_name='businesscard',
            name='title',
        ),
    ]
