# Generated by Django 5.2.5 on 2025-09-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_aboutimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Mission', max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='mission_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='AboutImage',
        ),
    ]
