# Generated by Django 5.2.5 on 2025-09-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About', max_length=255)),
                ('highlight', models.CharField(default='TRACO', max_length=255)),
                ('background', models.ImageField(upload_to='banners/')),
            ],
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='feature_icons/'),
        ),
    ]
