# Generated by Django 5.2.5 on 2025-09-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_banner_alter_feature_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Don’t Just Gain info', max_length=255)),
                ('highlight', models.CharField(default='Build Knowledge', max_length=255)),
                ('description', models.TextField(default='Whether you’re a new investor or a market expert, we’ve got something for everyone at the TRACO blog')),
                ('main_image', models.ImageField(upload_to='knowledge/')),
                ('star_icon_top', models.ImageField(blank=True, null=True, upload_to='knowledge/icons/')),
                ('star_icon_bottom', models.ImageField(blank=True, null=True, upload_to='knowledge/icons/')),
            ],
        ),
    ]
