# Generated by Django 5.2.5 on 2025-09-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_section_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partner_banners/')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
