# Generated by Django 5.2.5 on 2025-09-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_partnerbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='partner_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='PartnerBanner',
        ),
    ]
