# Generated by Django 5.2.5 on 2025-09-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_partner_delete_partnerbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome to the First Step of Becoming a TRACO Partner', max_length=200)),
                ('image', models.ImageField(upload_to='partners/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
