# Generated by Django 5.2.5 on 2025-09-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_partnerbanner_delete_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_text', models.CharField(help_text='Text in bold green', max_length=255)),
                ('description', models.TextField(help_text='Text below highlight')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
