# Generated by Django 5.2.5 on 2025-09-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_partnerbenefit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='features/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
