# Generated by Django 5.2.5 on 2025-09-05 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_footer_remove_sitelogo_name_sitelogo_alt_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('subheading', models.CharField(blank=True, max_length=200, null=True)),
                ('right_image', models.ImageField(upload_to='hero/')),
            ],
        ),
        migrations.CreateModel(
            name='HeroUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/users/')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='website.herosection')),
            ],
        ),
    ]
