# Generated by Django 5.2.5 on 2025-09-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_herosection_herouser'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='highlight/')),
                ('background_color', models.CharField(default='#000000', max_length=50)),
            ],
        ),
    ]
