# Generated by Django 5.2.5 on 2025-09-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_imageasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='backgrounds/')),
            ],
        ),
    ]
