# Generated by Django 5.2.5 on 2025-09-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_backgroundimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('balance', models.FloatField()),
                ('equality', models.FloatField()),
                ('risk_capital', models.FloatField()),
                ('drawdown_limit', models.FloatField()),
                ('evaluation', models.FloatField(default=15000)),
            ],
        ),
    ]
