# Generated by Django 5.2.5 on 2025-09-06 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='account',
            name='drawdown_used_pct',
            field=models.PositiveSmallIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='account',
            name='equality_left_pct',
            field=models.PositiveSmallIntegerField(default=31),
        ),
        migrations.AddField(
            model_name='account',
            name='goal_completed_pct',
            field=models.PositiveSmallIntegerField(default=11),
        ),
        migrations.AddField(
            model_name='account',
            name='goal_pending_pct',
            field=models.PositiveSmallIntegerField(default=89),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='drawdown_limit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='equality',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='risk_capital',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='MetricPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('balance', models.FloatField(default=0)),
                ('equality', models.FloatField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='website.account')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
