# Generated by Django 5.2.5 on 2025-09-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_account_avatar_account_drawdown_used_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Build a Strong Community', max_length=200)),
                ('description', models.TextField(default='Join a global network of passionate traders. Share strategies, learn from experts, and grow together in a supportive, success-driven environment.')),
                ('highlight_word', models.CharField(default='Strong', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='equality_left_pct',
        ),
        migrations.RemoveField(
            model_name='account',
            name='goal_pending_pct',
        ),
    ]
